### ISSUE TITLE
Live versie is geblocked

### ISSUE THREAD

**Issue by Theo-denBlanken** [Hensikt/Sorteer#1]
about:blank#blocked geeft en wit leeg scherm

**Comment by Hensikt** [comment]
Beste Theo,

Zou u nu de link nog eens willen proberen.

Met vriendelijke groet,
Bjørn Emmaneel, 27728
MD2B

Op wo 8 jan. 2020 13:16 schreef Theo den Blanken <notifications@github.com>:

**Comment by Theo-denBlanken** [comment]
Werkt nu wel
